version: "3.8"
services:
  tomcat:
    image: tomcat:9.0
    container_name: tomcat_app
    ports:
      - "8080:8080"
    volumes:
    volumes:
      - ./portfolio.war:/usr/local/tomcat/webapps/portfolio.war

